apiVersion: v0.1
workloads:
  nginx:
    runtime: podman
    agent: agent_A
    restartPolicy: ON_FAILURE
    tags:
      - key: owner
        value: Ankaios team
    runtimeConfig: |
      image: docker.io/nginx:latest
      commandOptions: ["-p", "8081:80"]
  hello1:
    runtime: podman
    agent: agent_B
    dependencies:
      filesystem_init: ADD_COND_SUCCEEDED
    runtimeConfig: |
      image: alpine:latest
      commandOptions: [ "--rm"]
      commandArgs: [ "echo", "Hello Ankaios"]
  hello2:
    runtime: podman
    agent: agent_B
    restartPolicy: ON_FAILURE
    tags:
      - key: owner
        value: Ankaios team
    runtimeConfig: |
      image: alpine:latest
      commandOptions: [ "--entrypoint", "/bin/sh" ]
      commandArgs: [ "-c", "echo 'Restarted on failure.'; sleep 2"]
  hello-pod:
    runtime: podman-kube
    agent: agent_B
    restartPolicy: NEVER
    tags:
      - key: owner
        value: Ankaios team
    runtimeConfig: |
      manifest: |
        apiVersion: v1
        kind: Pod
        metadata:
          name: hello-pod
        spec:
          restartPolicy: Never
          containers:
          - name: looper
            image: alpine:latest
            command:
            - sleep
            - 50000
          - name: greater
            image: alpine:latest
            command:
            - echo
            - "Hello from a container in a pod"
