name: Build
on:
  pull_request:

jobs:
  compare_requirements:
    name: Compare requirements with main branch
    permissions: write-all
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/eclipse-ankaios/devcontainer-base:1.0.1
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Compare requirement tracing reports
        id: compare
        run: |
          git config --global --add safe.directory $PWD
          just compare-requirements > req-results.txt
          if [ -s req-results.txt ]; then
            echo "diff=true" >> $GITHUB_OUTPUT
            echo '**Uncovered requirements found:**\n```' > comment.md
            cat req-results.txt >> comment.md
            echo '```\n' >> comment.md
          else
            echo "diff=false" >> $GITHUB_OUTPUT
          fi
      - name: Comment on PR if diff has been found and no label 'ignore-req-tracing' is present
        if: steps.compare.outputs.diff == 'true' && ! contains( github.event.pull_request.labels.*.name, 'ignore-req-tracing')
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-path: comment.md
